name: Test

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: yarn
      - run: yarn install --frozen-lockfile --check-files
      - name: Test Build # we don't have any other workflows to test build
        run: yarn build
      - name: Test Default with Provider
        run: yarn test:ci
